<?php
$a = 10;
$b = 5;
echo $a + $b; 
echo "<br>";
echo $a - $b; 
echo "<br>";
echo $a * $b;
echo "<br>"; 
echo $a / $b;
echo "<br>"; 
echo $a % $b; 
echo "<br>"; 
echo "=====";
$a = 10;
$b = 5;
echo $a == $b; 
echo "<br>";
echo $a != $b;
echo "<br>";
echo $a > $b;
echo "<br>";
echo $a < $b;
echo "<br>"; 
echo $a >= $b;
echo "<br>";
echo $a <= $b; 
echo "<br>"; 
echo"=====";
echo "<br>"; 
$a = 10; 
$b = 6;
echo $a & $b; 
echo "<br>";
echo $a | $b; 
echo "<br>";
echo $a ^ $b;
echo "<br>"; 
echo ~$a; 
echo "<br>";
echo $a << 2;
echo "<br>"; 
echo $a >> 1; 
echo "<br>"; 
echo"=====";
$a = true;
$b = false;
echo $a && $b;
echo "<br>";
echo $a || $b;
echo "<br>"; 
echo !$a; 
echo"=====";
$a = "Hello";
$b = "World";
echo $a . " " . $b; 
echo"=====";
$a = 5;
echo ++$a; 
echo $a++; 
echo $a; 
echo --$a; 
echo $a--; 
echo $a; 
echo"=====";
$a = array("apple", "banana");
$b = array("pear", "orange");
print_r($a + $b); 
var_dump($a == $b); 
var_dump($a === $b); 
var_dump($a != $b); 
var_dump($a <> $b); 
var_dump($a !== $b); 
echo"=====";
$a = 5;
$b = "5";
var_dump($a == $b); 
var_dump($a === $b); 
var_dump($a !== $b); 
echo "<br>"; 
